import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato } from "next/font/google";
import localFont from 'next/font/local';
import { ConditionalNavbar } from "@/components/conditional-navbar";
import "./globals.css";

const headingFont = localFont({
  src: './fonts/BBHSansHegarty-Regular.ttf', // sesuaikan path
  variable: '--font-heading',
});

const subheadingFont = localFont({
  src: './fonts/BricolageGrotesque-VariableFont_opsz,wdth,wght.ttf', // sesuaikan path
  variable: '--font-subheading',
});

const bodyFont = Lato({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-body',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bodyFont.variable} 
          ${subheadingFont.variable} ${headingFont.variable} antialiased`}
      >
        <ConditionalNavbar />
        {children}
      </body>
    </html>
  );
}
